// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://znssmbdsvqftxfmycpvd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpuc3NtYmRzdnFmdHhmbXljcHZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5MTA2NzcsImV4cCI6MjA2MDQ4NjY3N30.Uzgh3QD0aqcw0VT7jiqIgNxwJ1Ib33-EE_5Hw_8qdMs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY
);
